### ISSUE TITLE
Multiple room exit choices

### ISSUE THREAD

**Issue by mdr55** [axcore/axmud#12]
Is there an elegant way of dealing with an exit/portal that can deterministically land you in two different rooms, dependent on a mud-wide state?

if mud-state 1 -> entering this portal gets you to room 1
if mud-state 2 -> entering this (same) portal gets you to room 2

Some of the entry and destination rooms have distinct room descriptions.  Others don't.  I don't always of knowledge of mud-state before entering, although it would be apparent after entering. 

Now, I could just use the hot-keyed ;lrm -f  after entry at a distinct room and we're on the automap again.  But if there's a neater way without needing to write a massive script I'd be interesting in knowing it.

**Comment by axcore** [comment]
If the destination rooms have descriptions that the automapper can recognise, you can create a random exit: right-click the exit, select  **Edit exit**, in the new window click the **Random** tab, and then choose one of the options on the right. Probably, you would  click the **Room list** button, and add the numbers of the possible destination rooms in the box.

Otherwise you are looking at [scripting](https://axmud.sourceforge.io/share/docs/tutorial/index.html). You would need a trigger to detect the change of state. Whenever the trigger fires, your script would have to delete the existing exit and create a new one.

**Comment by mdr55** [comment]
thanks, closing
