### ISSUE TITLE
;alx and ;aex behaviour

### ISSUE THREAD

**Issue by mdr55** [axcore/axmud#14]
I've tried using ;alx (and tried ;aex as a last resort) to create a shadow exit as per chapter 15 of the guide - i'm not getting the responses I'm expecting.  The ;help entries are mostly aligned with ch15 as well.

I'm trying to create two possible paths from room 1 to room 2.  One is via the regular direction - let's say its "north".  The other one is "phase north" where it bypasses the door between room 1 and room 2 without needing an open command.

This seemed a lot like the example in 15.14 of chapter 15.  However:

;alx n phase north and ;alx n <phase north> resulted in respectively 

ERROR: ';allocateexit n phase n' : Couldn't find an unallocated exit matching 'phase n' in the automapper's current room

ERROR: ';allocateexit n <phase n>' : Couldn't find an unallocated exit matching 'phase n' in the automapper's current room

The allocate shadow function on the right click menu has been greyed out.

And trying to force the issue with ;aex <phase n> 1234 just causes a soft crash.

I've also tried using involuntary exits, which half worked - until the automapper realised there was an unknown direction associated with the new room desc and promptly said "automapper has lost track of the current location" and knocked me off automap.

I can work around this manually, but if the function can be fixed/reenabled next rev that'd be nice.  (or if I'm misunderstanding the syntax for alx)

**Comment by axcore** [comment]
This is slightly tricky, so let's start from the beginning. If the automapper sees a room description like this:

```
You are in a room.
Exits: west, east, foobar
```

... then the automapper will create an exit called "foobar", pointing in a random direction. Usually I right-click the exit and select **Allocate map direction**, but if you prefer, you could use **;alx foobar north** instead.

But it sounds like you are trying to create a virtual exit (one which is not visible in the room's description). There are a few ways to handle this; I would prefer the hidden exit method. Right-click the room, select **Add/set exits > Add hidden exit**, and then set it up like this:

![addhiddenexit](https://user-images.githubusercontent.com/37951926/152985077-44314bcb-a38d-471c-b4b7-4734138530c2.png)

Note that what you put in the second box **(Matches named exit**) doesn't matter very much in this case, just make sure the **Command sequence** is right.

Another way to handle this is to set **phase** as a movement command, so that the automapper can handle it automatically (and anywhere in the map). 

Type **;oov** to open the object viewer. In the tree in the left, click **Cages > All cages**, then click **cmd_world_aochoas** to select it, then click the **Edit** button.

In the new window, click the **Command** tab, then click one of the movement commands like **walk direction** to select it. In the box at the bottom, type **phase direction** and click the **Set new value** and **OK** buttons.

Another way to handle this is to update the dictionary to create new directions called "phase north", "phase south" and so on. In the main window's menu click **Edit > Edit dictionary... > Directions > Page 2**, click the **Add/Edit dir** button, add fill the boxes like this. 

![phasenorth](https://user-images.githubusercontent.com/37951926/152986734-b34b8176-3992-4452-a66f-ef88a3682f2d.png)

Note that if you could type **pn** as an abbreviation for **phase north", then **pn** should go in the **Abbreviation** box. Note that if the opposite direction is **phase south**, then that should go in the **Opposite dirs** box.

I haven't tested the second and third methods today, but they should work as described, if you feel like experimenting with them. The first method is probably the one you want, though.

**Comment by axcore** [comment]
>ERROR: ';allocateexit n phase n' : Couldn't find an unallocated exit matching 'phase n' in the automapper's current room

This is the error we would expect if you're trying to modify an exit that wasn't visible in the room's description.

>The allocate shadow function on the right click menu has been greyed out.

Shadow exits handle the situation in which you can type "east" or "pub" to enter the same room. Rather than cluttering up the map with duplicate exits, you can mark one of them as a shadow exit so that it isn't actually drawn (but the automapper still knows how to handle it).

>And trying to force the issue with ;aex 1234 just causes a soft crash.

What is the precise command you are using? I tried **;aex 1234 \<phase north\>** on your map and didn't see a soft crash.

**Comment by mdr55** [comment]
> I haven't tested the second and third methods today, but they should work as described, if you feel like experimenting with them. The first method is probably the one you want, though.

Method 2 (changing the walk -> phase command) worked exactly as hoped, it seems to work anywhere and there isn't a need to modify rooms individually. 

Couldn't get method 1 or 3 to work (see more on method 1 in next comment).  Dictionary change didn't work - but I didn't mess around with it too long seeing as method 2 worked.

**Comment by mdr55** [comment]
Below is a paste of the crash notes:

WARNING: Exiting subroutine via last at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
WARNING: Exiting subroutine via last at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
WARNING: Exiting subroutine via last at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
WARNING: Exiting subroutine via last at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
WARNING: Exiting subroutine via last at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
WARNING: Exiting eval via last at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
WARNING: Exiting subroutine via last at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
ERROR: Label not found for "last OUTER" at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
MAP: The automapper's current room has been reset
 
Because of a Perl error, Axmud internal processes have been suspended across all sessions. (This will prevent you from seeing the same error message again and again, and will perhaps protect your stored data from getting corrupted. If there are several sessions open, the error is sometimes visible only in one session.)
 
Most errors of this kind are caused by invalid patterns (regular expressions) in your interfaces (triggers, aliases, macros, timers and hooks). You can often correct them by opening an 'edit' window and by replacing the invalid pattern with a valid one or by deleting it altogether.
 
When you are ready, you can use the ';restart' command to return Axmud to a more-or-less functional state.
 
---
 
Too long, didn't read? Just type:   ;restart
 
WARNING: *** unhandled exception in callback:
WARNING: ***   Label not found for "last OUTER" at /usr/local/share/perl/5.30.0/Games/Axmud/Obj/WorldModel.pm line 17773.
WARNING: ***  ignoring at /usr/share/perl5/Gtk3.pm line 572.

the command was ";aex \<phase north\> 831"  I was in room 831 (hopefully its in your copy of the map?)  The door north was closed, and the mud doesn't show closed exits on the exits in the room description.  Room 831 in my version already has a link to the room to the north.

I don't know if its digging into something unnecessarily since there appears to be a solution (aside from potentially more graceful exception handling)

**Comment by axcore** [comment]
The crash is the result of a typo. You can replace your copy of the file **../lib/Games/Axmud/Obj/WorldModel.pm** with the one I uploaded to Github today, or you can just edit it yourself, replacing line 17764:

`           foreach my $otherExitNum ($roomObj->ivValues('exitNumHash')) {
`

...with this:

`            OUTER: foreach my $otherExitNum ($roomObj->ivValues('exitNumHash')) {
`

I am still a couple of weeks away from being able to do a full release, by the way.

**Comment by axcore** [comment]
Regarding the failure of method 1: I thought about logging in to Age of Chaos with a newbie character, in order to test the exit for myself. But I'm not sure if a newbie character would stay alive for very long in a Kobold Castle.

I did try a very similar situation at a different mud, though, and it seems to work as expected. There is a normal north exit, and a "hidden" exit drawn as northeas and using the command "crawl north" (very similar to your "phase north"):

1. I can type "crawl north", and the automapper moves to the new location
2. I can type "northeast", Axmud sends "crawl north" to the MUD, and the automapper moves to the new location

Can you be more precise? Which of these two commands fails?

**Comment by mdr55** [comment]
Thanks, it makes sense to me now, I was effectively trying to get the commands to make a north exit and somehow use it as both a "normal"  exit and a phase alternative simultaneously  (which sounds silly now), whereas the idea is to actually "hijack" one of the automapper's unused exits, and map it to the alternative and hidden exit path on the MUD.  Its what I do with portals (like "enter portal" or "enter hole") but I never made the connection until you spelt it out just then :)

It worked on a live test I just did, but seeing as method 3 worked universally without needing to do a per room change, I'll stick with that.  I can see where this will come in handy in a few special case rooms in the future though.

Thanks very much for the walk through!

Closing comment as there's nothing left open I think.
