### ISSUE TITLE
Pre-Configured Support for Akanbar

### ISSUE THREAD

**Issue by macjabeth** [axcore/axmud#16]
Hello! With its recent awakening, [Akanbar](https://www.akanbar.com/) has been drawing many players both veteran and new to its lands.

We've had some visually-impaired folks joining the fun recently and were hoping to get Akanbar added as a pre-configured MUD in Axmud so they can hit the ground running. 🙂

Is this doable? If so, please let me know if there is anything I can do or provide to help in these effort!

Thank you.

**Comment by axcore** [comment]
The play button at the bottom of the page on https://www.akanbar.com/ is broken. (At least on Firefox 108.0).

**Comment by axcore** [comment]
Ok, I had a look around Akanbar. 

The main reason to set up a pre-configured world, is so that the automapper can be used straight away. The automapper works by checking each line as it's received, looking for a pattern like `You can progress north and south`. I's not a problem if a list of directions like `north, south, southwest, east, up and down` are split over two lines, but it is a problem if the `You can progress` part is split over two lines. I'm not sure, at the moment, how that can be overcome.

I experimented with the screenreader on/off commands, and with verbose/brief room descriptions, with the same problem.

I noticed that room titles are displayed in yellow. If that is the _only_ yellow text used in the game, that would be enough to get the automapper working. (Probably.)

If your concern is not a working automapper, but finding some way to put Akanbar on the mudlist where blind users can easily find it, then that's a different question. It occurs to me that a better solution would be a simple way for people to create a tweaked Axmud installer that auto-connects to a particular MUD, then you can simply make the tweaked version available for download from your website. I'll have a think about how that might be done.

**Comment by macjabeth** [comment]
@axcore Thank you for the update and guidance! The creator (Zycandos) has told me he will work on fixing the exit lines tomorrow. Should I keep you posted on when the exit lines have been fixed?

As for the yellow room titles, there are a few other bits of text in the game that are yellow. For example, there is an ability that grants the player divine sight and allows them to see player locations on the WHO list:

<img width="656" alt="Capture 2022-12-20 at 23 00 01@2x" src="https://user-images.githubusercontent.com/8473052/208825301-b1fc5469-0f06-4638-bf18-50e448f3be62.png">

Would those locations/text interfere with the automapper?

And in regards to the modified Axmud installer, that could be a possibility! What exactly would that entail, and how up-to-date would the modified installers be in comparison to the official Axmud installer?

**Comment by axcore** [comment]
There is no need to "fix" the exit lines, they are fine just as they are. There are plenty of other MUDs that merge the room description, contents list and exits all into one paragraph.

I can think of several tweaks that would work just as well:

1. `help screenreader ` claims that room descriptions are sent as multiple lines only when `screenreader off` applies, but I can't see any different between the two settings. If it were possible to turn off line formatting (currently every line is restricted to 80 characters or so), that would solve the problem 
2. Could add a setting to show the "You can progress north" sentence in a colour that isn't in use elsewhere. Bold yellow, perhaps.
3. There are several MUD protocols that add invisible text to mark room descriptions. MUDs that implement them tend to do so partially, adding just the features they need. If [MXP](https://www.zuggsoft.com/zmud/mxp.htm#Implementation%20Details) were chosen, for example, it wouldn't be much work to surround the exit list with `<RExits> </Rexits>` tags, sent only when the user has typed `mxp on` or something.

The WHO list, as it stands, would not interfere: Axmud can look for lines that _begin_ with yellow text, not just contain it. And we can easily ignore any lines containin `(at:`

About the installer: if you open a terminal window and type something like `perl axmud.pl akanbar.com`, then Axmud will connect to that MUD automatically without opening the Connections window. Users on MS Windows are running a .bat file, so it would be as simple as tweaking that .bat file, then re-compiling the installer. In theory at least, I haven't actually tried it yet.

**Comment by axcore** [comment]
Yeah, buzz me as often as you like.

**Comment by axcore** [comment]
I checked Akanbar a few days ago, but it seems to be still incompatible with the automapper. Because of inactivity in this issue, I'll go ahead and close it, but feel free to re-open if you want to.
