### ISSUE TITLE
Character names can't contain spaces

### ISSUE THREAD

**Issue by AxelTerizaki** [axcore/axmud#17]
I'm trying to create a profile for a character on a MUSH I'd like to connect to with axmud, but it won't let me add a space in the character name, saying it's invalid, although the MUSH allows this (if a character name has a space, it should be enclosed in "" on login)

Thanks for creating this MUD client!

**Comment by axcore** [comment]
The solution is to write your own login script, rather than relying on the standard MUSH login. 

There are several ways to do it, for example using [missions](https://axmud.sourceforge.io/share/docs/guide/ch09.html). If you tell me which MUSH you're using then I can write the script for you.

**Comment by AxelTerizaki** [comment]
This seems a bit convoluted just to login, and not very user friendly :/ Isn't it easier to just allow the login field in the dialog box to have spaces in names ? Just delete that check ?

**Comment by axcore** [comment]
Unfortunately it's not that simple, because there are a lot of features dependent on character profiles, all of which would have to be updated. Whereas a login script would take us about 60 seconds.

**Comment by axcore** [comment]
v2.0.0, release today, adds this feature.

All character profiles now have a nickname, as well as a name. By default, they're the same, but nicknames can contain any characters (including spaces).

To change the nickname, click Edit > Edit current character... > Settings > Page 1.

Automatic logins now use the nickname, instead of the name. So if the profile **Gandalf** has a nickname **Gandalf the Great**, then it is **Gandalf the Great** that is used during logins.

This seems to be what you wanted, so I'll go ahead and close the issue.
