### ISSUE TITLE
Map: Moving Labels and/or Adding Labels to Rooms

### ISSUE THREAD

**Issue by RockguyRy** [axcore/axmud#7]
Could we be able to move labels? I don't see any documentation on being able to move them to a position we'd like. Or make sure they are all even.

Also adding like a 5 char max label to post inside a room would be fantastic. The mud I'm on has an overworld map that is on a grid-system and I'd like to show the numbers on my map...

**Comment by axcore** [comment]
You can drag anything on the map, including labels:

1. Hold down your ALT-GR key, and drag it
2. If you don't have an ALT-GR key, click the drag mode button to enable drag mode, move your labels, then click the same button again to disable drag mode

Chapter 15 of the [Guide](https://github.com/axcore/axmud/blob/master/share/docs/guide/ch15.mkd) explains dragging and dropping.

If tooltips are turned on, you can let your mouse hover over a room to get Axmud's grid coordinates. You can quite easily move rooms on the map so that they align with the game's grid coordinates (more or less). Select all the rooms, then **Rooms > Move rooms/labels > Move in direction...**

You can add a tag to a room, right-click the room and select **Set room text > Set room tag...**. The maximum size is 16 characters, but no-one is forcing you to type more than 5. The tag moves along with the room when it is dragged, and its position can be reset by right-clicking it and selecting **Reset position**.

The type of text displayed inside the room box can be set with **View > Room interiors**. You can't display the grid coordinates or room tags there at the moment, but that would be quite easy to add. 

Existing labels can be lined up with each other by clicking **Labels > Label alignment > Align horizontally/vertically**

**Comment by axcore** [comment]
v1.3.019 was released today, which fixes a couple of major automapper bugs which affect dragging things on the map, so you should definitely upgrade.

I also took the opportunity to implement your other requests.

[Room tags](https://github.com/axcore/axmud/blob/master/share/docs/guide/ch15.mkd#15.19) can now be displayed inside the room box: select **View > Room interiors > Draw room tag**.

Alternatively, you can display grid coordinates there: **View > Room interiors > Draw grid coordinates**. These are the coordinates in the automapper window; to [synchronise](https://github.com/axcore/axmud/blob/master/share/docs/guide/ch15.mkd#15.25.1) them with the game's coordinates, click **Rooms > Other room features >
    Synchronise grid coordinates...**
