### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by mdr55** [axcore/axmud#8]
;addteleport (with some valid? parameters) and centremap (from the view menu) both causes soft crashes and requires a ;restart

Seemingly unable to modify room links manually, its all greyed out.  Work around is either move a room on the automapper, walk into it to force a link, and then move room back, OR try to drag a room exit to another room.  The latter is finicky and not always successful, haven't been able to find out success conditions - might have been from not understanding how some of the background smarts work, sometimes the linking works great.

Deleting a region also caused a soft crash using the menu option (region is gone after ;restart though).  Deleting a region via ;drn seems to work fine.

Its possible for a region to become unusable.  Automapper created a link I didn't like - I deleted the room and it crashed out, and any time entering the region also caused a soft crash.  From memory it was some sort of a circular link.

When transitioning between levels, especially if there are multiple ups/downs, sporadically parts of the region don't redraw.  It looks like you've stepped into a new level with a single room on that level when its all been mapped out.  Forcing a region redraw seems to be a workaround.

Another issue with moving between levels manually is that the grid keeps shifting (and so have to manual drag the scroll bars to find the rooms again), and with centering map causing a soft crash its a usability problem in terms of navigation.

Using a linux compile of v1.3.019  edit - on ubuntu, compiled using debian instructions

**Comment by axcore** [comment]
>;addteleport (with some valid? parameters) and centremap (from the view menu) both causes soft crashes and requires a ;restart

Connect to the world (in online or offline mode). In the automapper window, click **File > Save/Export world model** so we have a backup copy of the broken map.

Then try the **;testmodel** command. If it reports problems, you can fix those problems by typing **;testmodel -f**. If that doesn't resolve your crashes, then I would be happy to examine your map manually.

>Seemingly unable to modify room links manually, its all greyed out.

What is greyed out, where?

>When transitioning between levels, especially if there are multiple ups/downs, sporadically parts of the region don't redraw

This is a known bug which I haven't been able to resolve yet, because it's so difficult to reproduce.

**Comment by mdr55** [comment]
thanks very much - i ran testmodel and it automagically cleared up most of the issues - the one that it couldn't I just deleted the affect room and it was sorted.  So now centre map function works without crashing.

teleport now gives the following error msg:
ERROR: Can't locate object method "add_teleport" via package "Games::Axmud::Obj::WorldModel" at /usr/local/share/perl/5.30.0/Games/Axmud/Cmd.pm line 80463.
for reference, I used ";addteleport home recall"  home is a room tag I've placed on a room, and recall is command that the mud recognises.


on room links, if I just pick any exit (whether its a broken or fully formed one), and edit the exit model, the 1st tab "Name" with all the general properties including destination room #, Twin exit #, etc, is completely greyed out - every single field.  I don't know if I'm misunderstanding the purpose of that tab.

**Comment by axcore** [comment]
>teleport now gives the following error msg:

Confirmed. It looks like the ;addteleport command is trying to call some code that doesn't exist.

You can use the GUI as a workaround. In the automapper window, click **Edit > Edit world model... > Model > Page 6**.  The two boxes act just like the two arguments to ;addteleport. 

(I think that will work, but as I have no internet today, I haven't tested it.)

> and edit the exit model, the 1st tab "Name" with all the general properties including destination room #, Twin exit #, etc, is completely greyed out

I'm afraid that's intentional, the automapper window's code is already 50,000 lines long; if I were to add the same functionality to the edit window, that would be an extra 50,000 lines of code.

To modify those things, you have to drag items around on the map, or right-click those items, or use the autormapper wind'w menu.

**Comment by mdr55** [comment]
the workaround is functional with the GUI.  The ;teleport command itself worked - the recall command was sent to the mud, the the automapper went to the right room, but 10x of the following purple messages also sprang up
IMPROPER ARGS: Games::Axmud::Obj::Dict->ivExists() Games::Axmud::Obj::Dict=HASH(0x55f6e85be048) combDirHash <<undef>>
IMPROPER ARGS: Games::Axmud::ModelObj::Room->ivExists() Games::Axmud::ModelObj::Room=HASH(0x55f6e9633488) exitNumHash <<undef>>

This happens regardless of using room tag or room # directly.  The 1st pair appears after the recall command was sent.  The mud then respond with the room desc of having moved to the home room, and then 9x pairs of the above above warnings, followed by misc room outputs from the mud and finally the mud prompt.

;teleport invoked with an invalid room argument gets 2x pairs of the warnings, first immediately after entry, followed by a mud non-sense response, and then by another pair of the warning.  Automapper does not change state.
 
;testmodel at this point shows no errors or fixes


edit:  further testing on this.  If automapper/locator is not engaged, there are no warning messages and the recall command is sent.  The warnings only happen if locator/automapper is tracking movement.
.



Thanks for the confirmation re: editing links, I've now kind of developed a process that works ok for rooms on the same level.

**Comment by axcore** [comment]
>the workaround is functional with the GUI. The ;teleport command itself worked - the recall command was sent to the mud, the the automapper went to the right room, but 10x of the following purple messages also sprang up

Ok give me a couple of days, I'll try to fix the broken Axmud code.

**Comment by axcore** [comment]
Ok, I have fixed the teleportation problems, ;teleport seems to be working as expected now.

I have also inserted a check for the Glib warnings, but I can't reproduce those warnings so I don't know if it will work.

How exactly did you install axmud? I am in the middle of moving house, I can upload source code to github without problems, but producing a new .DEB package might be a bit tricky.

**Comment by mdr55** [comment]
Thanks for fixing the code - I compiled from the source as per instructions (for Debian).  I assume if I rerun those instructions with the new .tar.gz, it'll overwrite the current install?

**Comment by axcore** [comment]
I uploaded the fixed source code to github, so you can try installing that. It should contain exactly the same files as your previous install, and so completely overwrite it.

If you did make a copy of the broken map, I would be happy to examine it, so I can work out what the problem was, but if you don't want to share it that's ok too.

**Comment by mdr55** [comment]
Can confirm that all is fixed!  ;teleport works as described and the warnings have been suppressed. Thanks again.
